### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by Locho18** [AMereBagatelle/AFKPeace#3]
The game crashes when you use the "/afkpeace" command on multiplayer servers and on single-player
Game Crash Report Below
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 6/29/20 5:37 PM
Description: keyPressed event handler

java.lang.NoSuchMethodError: net.minecraft.class_2585.method_10854(Lnet/minecraft/class_124;)Lnet/minecraft/class_2561;
	at net.minecraft.class_746.handler$zjj000$onChatMessage(class_746.java:2269)
	at net.minecraft.class_746.method_3142(class_746.java)
	at net.minecraft.class_437.method_25425(class_437.java:309)
	at net.minecraft.class_437.method_25427(class_437.java:302)
	at net.minecraft.class_408.method_25404(class_408.java:98)
	at net.minecraft.class_309.method_1454(class_309.java:350)
	at net.minecraft.class_309$$Lambda$5664/1990272837.run(Unknown Source)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_309.method_1466(class_309.java:348)
	at net.minecraft.class_309.method_22678(class_309.java:438)
	at net.minecraft.class_309$$Lambda$5514/1236782350.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_309.method_22676(class_309.java:438)
	at net.minecraft.class_309$$Lambda$2726/308137953.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1041)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_746.handler$zjj000$onChatMessage(class_746.java:2269)
	at net.minecraft.class_746.method_3142(class_746.java)
	at net.minecraft.class_437.method_25425(class_437.java:309)
	at net.minecraft.class_437.method_25427(class_437.java:302)
	at net.minecraft.class_408.method_25404(class_408.java:98)
	at net.minecraft.class_309.method_1454(class_309.java:350)
	at net.minecraft.class_309$$Lambda$5664/1990272837.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_408
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_309.method_1466(class_309.java:348)
	at net.minecraft.class_309.method_22678(class_309.java:438)
	at net.minecraft.class_309$$Lambda$5514/1236782350.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_309.method_22676(class_309.java:438)
	at net.minecraft.class_309$$Lambda$2726/308137953.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)

-- Affected level --
Details:
	All players: 1 total; [class_746['Locho_Master'/126, l='ClientLevel', x=-15.28, y=175.00, z=-205.05]]
	Chunk stats: Client Chunk Cache: 1089, 764
	Level dimension: minecraft:the_nether
	Level spawn location: World: (32,67,-208), Chunk: (at 0,4,0 in 2,-13; contains blocks 32,0,-208 to 47,255,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 3228660 game time, 3228660 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2181)
	at net.minecraft.class_310.method_1514(class_310.java:672)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 746863112 bytes (712 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		afkpeace: AFKPeace 4.2.0
		appleskin: AppleSkin 1.0.11
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.5.6
		cotton-client-commands: Cotton Client Commands 1.0.0+1.15.2
		durabilityviewer: Giselbaers Durability Viewer 1.16-fabric0.13.1-1.7.1
		fabric: Fabric API 0.14.0+build.371-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a977402
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.0.0+b0993bc102
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea86602
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.5+e00ecb5f02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad602
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.2+4d66bed502
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.5+059ea8667c
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e02
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
		fabricloader: Fabric Loader 0.8.8+build.202
		gbfabrictools: GBfabrictools 1.2.2+1.16
		lightoverlay: Light Overlay 5.4.0
		litematica: Litematica 0.0.0-dev.20200627.000333
		malilib: MaLiLib 0.10.0-dev.21+beta.2
		minecraft: Minecraft 1.16.1
		modmenu: Mod Menu 1.12.2+build.17
		orderly: Orderly 2.0.0-alpha.10-1.16
		roughlyenoughitems: Roughly Enough Items 4.5.5
		shulkerboxtooltip: Shulker Box Tootip 2.1.0+1.16.1
		tweakeroo: Tweakeroo 0.10.0-dev.20200624.214908
		voxelmap: VoxelMap 1.10.1
		wi_zoom: WI Zoom 1.2-MC1.16.1
	Launched Version: fabric-loader-0.8.8+build.202-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.4549, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, fabric/fabric-tool-attribute-api-v1
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz

**Comment by AMereBagatelle** [comment]
It seems this is a problem with a `cotton-client-commands`.  I bundle this dependency to provide the `/afkpeace` command.  I have notified the developers of `cotton-client-commands` of the problem and they are working on it.

**Comment by AMereBagatelle** [comment]
It has been fixed, a new build will be uploaded to CurseForge soon with the fix.
